spring:
  datasource:
        url: jdbc:mysql://localhost:3306/gradu-desgin
        username: root
        password: 207416
        driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8081
cxf:
  path: /authorization

#百度API-properties
gateway:
      baidu:
            appId: 11025543
            apiKey: CBEGsyu7QC4PlGz6H4cs8h0O
            secretKey: U272CkcFRDDnUfGGCKtVmhbuAzfP3yIx

mybatis:
    type-aliases-package: vens.ai.graduate.design.authorization.entity
    mapper-locations: classpath:mybatis_mappers/*.xml

logging:
  config: classpath:log/log4j2.xml


#c3p0
c3p0:
  jdbc-url: jdbc:mysql://localhost:3306/gradu-desgin
  user: root
  password: 207416
  driver-class: com.mysql.jdbc.Driver
secourity:
  privateKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALazmK7Anx81ayMQouIGVY8yt/dO0cdGCcSbUHHd8Rci\\nIgrOeLq2xjpQGP6NpZ9TRwGBZkTu1Sw8HIwjU5LnaK8CAwEAAQ==
## 通过配置设置c3p0数据源
#spring.datasource.type=com.mchange.v2.c3p0.ComboPooledDataSource
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/gradu-desgin
#spring.datasource.username=root
#spring.datasource.password=1234
#
